### ISSUE TITLE
overwrite files missing!

### ISSUE THREAD

**Issue by mu-cai** [alex04072000/SOLD#2]
In your README, you said that `Please overwrite tfoptflow/model_pwcnet.py and tfoptflow/model_base.py using the ones in this repository.`, but there are no files related to these two.
Thanks!

**Comment by christian-cahig** [comment]
Same problem here

**Comment by mu-cai** [comment]
### Hi I think we can use the new repo https://github.com/alex04072000/ObstructionRemoval 
This one can work. @christian-cahig

**Comment by christian-cahig** [comment]
> ### Hi I think we can use the new repo https://github.com/alex04072000/ObstructionRemoval
> This one can work. @christian-cahig

Thanks @mu-cai.

I also found [this Colab notebook](https://colab.research.google.com/drive/1iOKknc0dePekUH2TEh28EhcRPCS1mgwz) from [Jia-Bin Huang's publications page](https://filebox.ece.vt.edu/~jbhuang/publications.html). I hope this helps.
